services:
  app:
    container_name: smart-health-links-portal
    build:
      context: .
      target: dev
      dockerfile: docker/development/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - /app/.next
    ports:
      - '3000:3000'
    networks:
      - smart-health-links-portal-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - smart-health-links-portal-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    volumes:
      - ./import/config/shlp:/opt/keycloak/data/import
    restart: always
    depends_on:
      - postgres
    networks:
      - smart-health-links-portal-network

  hapi-fhir:
    image: jembi/hapi:v7.0.3-wget
    ports:
      - 3447:8080
    networks:
      - smart-health-links-portal-network
    volumes:
      - hapi_fhir_data:/var/lib/hapi-fhir
    environment:
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.bulk_export_enabled=true
      - HAPI_FHIR_IPS_ENABLED=true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 30s
      timeout: 10s
      retries: 3
    image: jembi/hapi:v7.0.3-wget
    ports:
      - 3447:8080
    networks:
      - smart-health-links-portal-network
    volumes:
      - hapi_fhir_data:/var/lib/hapi-fhir
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  smart-health-links-portal-network:
    driver: bridge
