name: Tests with Coverage Check

on:
  push:
    branches:
      # - '*'
      - 'main'
  pull_request:
    branches:
      - main
      - fix/production-build-prisma-field-encryption

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest Tests
        run: yarn test --collectCoverage=false

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
          id: get_branch  # Add an ID to this step to reference its output
          run: |
            echo "::set-output name=branch_name::${{ github.head_ref }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tag
        if: ${{ gsteps.get_branch.outputs.branch_name != 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: docker/production/Dockerfile
          tags: jembi/smart-health-links-portal:${{ steps.get_branch.outputs.branch_name }}

      - name: Build and push latest
        if: ${{ steps.get_branch.outputs.branch_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: docker/production/Dockerfile
          tags: jembi/smart-health-links-portal:latest

  # coverage:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     # - name: For act to work (local testing)
  #     #   run:  npm -g install yarn

  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0  # Fetch all history for accurate comparison

  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
  #         cache: 'yarn'

  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Checkout Main Branch
  #       uses: actions/checkout@v3
  #       with:
  #         ref: main
  #         path: main

  #     - name: Temp - Install Jest
  #       run:  yarn add jest
  #     - name: Run Jest Coverage for Main
  #       working-directory: main
  #       run: yarn test --coverage

  #     - name: Run Jest Coverage for Current Branch
  #       run: yarn test --coverage

  #     - name: Get Coverage Difference
  #       id: coverage-difference
  #       run: |
  #         if [[ -f ./coverage/lcov.info ]] && [[ -f ./main/coverage/lcov.info ]]; then
  #           echo "Current Coverage:"
  #           currentCoverage=$(cat ./coverage/lcov.info | yarn jest-coverage-badges -r lcov | grep -oP '(?<=coverage: )\d+')
  #           echo "$currentCoverage"

  #           echo "Main Coverage:"
  #           mainCoverage=$(cat ./main/coverage/lcov.info | yarn jest-coverage-badges -r lcov | grep -oP '(?<=coverage: )\d+')
  #           echo "$mainCoverage"

  #           diff=$(echo "$mainCoverage" "$currentCoverage" | awk '{print ($2-$1)}')
  #           echo "::set-output name=diff::$diff"
  #         else
  #           echo "One or both coverage reports are missing. Skipping comparison."
  #           echo "::set-output name=diff::0"  # Treat missing reports as no change
  #         fi

  #     - name: Fail if Coverage Decreased
  #       if: steps.coverage-difference.outputs.diff < 0
  #       run: |
  #         echo "🛑 Coverage decreased compared to main!"
  #         exit 1

  #     - name: Upload Coverage to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}

  #     - name: Coverage Summary
  #       run: |
  #         echo "✅ Jest coverage passed with:"
  #         echo "$(cat ./coverage/lcov.info | yarn jest-coverage-badges -r lcov)"
  #         echo "View detailed coverage report on Codecov."
